import type { Metadata } from "next";
import { Toaster } from 'sonner';

import "./globals.css";

export const metadata: Metadata = {
  title: "JWT_Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster closeButton theme="dark" position="top-center" />
      </body>
    </html>
  );
}
